ifndef::full-version[]
include::../headers.adoc[]
:toc: macro
:toc-title: What's the plan for this lesson?

toc::[]
endif::full-version[]

== Lesson 5: When several containers talk to each other.

=== External network

==== Direct communication

How to make 2 containers talking to each other via the network?
Which IP address to use? `127.0.0.1`? `random.random.random.random`?

.Let's use a case of study:

First, run a simple nginx container with `docker run -d --name webapp nginx`.

Then run, with the `-it` param, a `gscheibel/docker4devs:curl` container (which is simply a glorified Debian with curl installed).

.How to ping the nginx container from the curl one?

By default, the docker engine manages a `bridge` network which is accessible from all the containers.
Try to inspect the `webapp` container using `docker inspect webapp`.

At the end, you should be able to see the network configurations for this container.

:ipaddress: 172.17.0.4
[source,json,subs="attributes, verbatim"]
----
{
  "Networks": {
      "bridge": {
          "IPAMConfig": null,
          "Links": null,
          "Aliases": null,
          "NetworkID": "ade9ac6b5007c77445544784f05f423d446e764c840c8355221547981c9cd6c3",
          "EndpointID": "5307c8dab802788a78e3fba5d82c8480360bd6a125ac95690c8fcb15773bcf3f",
          "Gateway": "172.17.0.1",
          "IPAddress": "{ipaddress}", <1>
          "IPPrefixLen": 16,
          "IPv6Gateway": "",
          "GlobalIPv6Address": "",
          "GlobalIPv6PrefixLen": 0,
          "MacAddress": "02:42:ac:11:00:04",
          "DriverOpts": null
      }
  }
}
----

<1> The `IPAddress` field gives you the IP address to use to connect to this container.

Now we have the ip address, go to your `docker4devs:curl` container and try:

[source, subs="attributes"]
$ curl -I {ipaddress}

.Expected output

[source]
----
HTTP/1.1 200 OK
Server: nginx/1.13.5
Date: Tue, 31 Oct 2017 13:17:40 GMT
Content-Type: text/html
Content-Length: 612
Last-Modified: Tue, 08 Aug 2017 15:25:00 GMT
Connection: keep-alive
ETag: "5989d7cc-264"
Accept-Ranges: bytes
----

==== Specific network

Knowing each container's IP address is cumbersome and doesn't isolate much (inside of a same host).
To mitigate this situation, the engine provides the https://docs.docker.com/engine/reference/commandline/network/[`network` command].

The idea is to create a subnetwork (bridge by default) which  will be shared by several containers.
Unlike the default bridge, container within a subnetwork can be accessed by their name.

To associate a subnetwork a container (at creation time), the `--network=[NAME]` parameter of the `docker run` command can be used.

.Exercise

Create a subnetwork named `d4d-network`.
Start a new nginx container named `webapp` and associate it to the `d4d-network` subnetwork.
Finally do the same with a `curl` container.

Then in your `curl` container you should be able to run:

.Expected result
[source]
.In the curl container
----
$ curl -I webapp:80

HTTP/1.1 200 OK
Server: nginx/1.13.5
Date: Tue, 31 Oct 2017 13:39:35 GMT
Content-Type: text/html
Content-Length: 612
Last-Modified: Tue, 08 Aug 2017 15:25:00 GMT
Connection: keep-alive
ETag: "5989d7cc-264"
Accept-Ranges: bytes
----

include::solutions.adoc[tags=subnetwork]

=== Complex builder container

==== Triggering actions on a child image at build time

:builder: d4d:builder

The https://docs.docker.com/engine/reference/builder/#onbuild[ONBUILD] instruction provides a way to defer the execution of some instructions.
The instruction will be executed in the context of a downstream build.

For example, you have a an image `{builder}` declared as:

:onbuild: RUN echo "Hello world"
[source, subs="attributes"]
----
FROM debian

ONBUILD  {onbuild} <1>
----

<1> The `{onbuild}` instruction is executed only when the below image is built.

When the engine builds the following image:

[source]
FROM  {builder}

All the `ONBUILD` instructions are being executed *first* and in this example the output would be:

[source, subs="attributes"]
----
$ docker build -f child .

Sending build context to Docker daemon  3.072kB
Step 1/1 : FROM {builder}
# Executing 1 build trigger...
Step 1/1 : RUN echo "Hello world"
 ---> Running in f7e5885bd628
Hello world <1>
 ---> 1cee673766ae
Removing intermediate container f7e5885bd628
Successfully built 1cee673766ae
----

<1> The result of the `ONBUILD` instruction set in {builder}

==== Build and run with containers

What if my build environment doesn't support the language / environment my application is build on top of?

For example, you want your new Go application to be built by your CI pipeline.
But you don't necessarily want to install the Go environment in each of your Jenkins slaves.

One of the solution is to build your binary in a container.
Then you can run your application in another container.

===== 2 containers + 1 script = old way

The first approach is (was) to build a first image named `builder` to produce the binary.
Then you have to create a container which you will extract the binary from.

And finally, you build your `runner` image which will copy the produced binary.

In terms of Dockerfile you have:

[source]
.The builder image
include::examples/old-builder/dockerfile.build[]

[source]
.The runner image
include::examples/old-builder/dockerfile.run[]

[source]
.The script
include::examples/old-builder/build.sh[]

===== Multistage build
